create table type
(
    id int generated by default as identity,
    val text
)

create table movie
(
    id int generated by default as identity,
    title text,
    year date,
    runtime time,
    plot text,
    awards text,
    tid int,
    box_office money,
    poster_img bytea,
    constraint pk_movie primary key (id),
    constraint fk_type foreign key (tid) references type (id)
);

create table genre
(
    id int generated by default as identity,
    name text,
);

create table director
(
    id int generated by default as identity,
    first_name text,
    last_name text,
);

create table actor
(
    id int generated by default as identity,
    first_name text,
    last_name text,
);

create table lang
(
    id int generated by default as identity,
    name text,
);

create table ratings_agency
(
    id int generate by default as identity,
    name text
);

create table movie_ratings
(
    mid int,
    aid int, -- agency id
    val float, -- normalized
    constraint movie_genre_pk primary key (mid, aid),
    constraint movie_ratings_movie_fk foreign key (mid) references movie (id),
    constraint movie_ratings_agency_fk foreign key (aid) references ratings_agency (id)
);

create table movie_genre
(
    mid int,
    gid int,
    constraint movie_genre_pk primary key (mid, gid),
    constraint movie_genre_movie_fk foreign key (mid) references movie (id),
    constraint movie_genre_genre_fx foreign key (gid) references genre (id)
);

create table movie_director
(
    mid int,
    did int,
    constraint movie_director_pk primary key (mid, did),
    constraint movie_director_movie_fk foreign key (mid) references movie (id),
    constraint movie_director_director_fk foreign key (did) references director (id)
);

create table movie_actor
(
    mid int,
    aid int,
    constraint movie_actor_pk primary key (mid, aid),
    constraint movie_actor_movie_fk foreign key (mid) references movie (id),
    constraint movie_actor_actor_fk foreign key (aid) references actor (id)
);

create table movie_lang
(
    mid int,
    lid int,
    constraint movie_lang_pk primary key (mid, lid),
    constraint movie_language_movie_fk foreign key (mid) references movie (id),
    constraint movie_language_lang_fk foreign key (lid) references lang (id)
);